### ISSUE TITLE
ошибка при разворачивании

### ISSUE THREAD

**Issue by 9270440** [bezumkin/orbita#21]
нет настроек для перенаправки портов node.js
по умолчанию всегда на 3000 порту стартует у меня был занят (

добавил настройку в .env
NODE_PORT=3001
NUXT_PORT=3001
NITRO_PORT=3001
вроде завелось 
в nginx все корректно 

и при работе получил 503 ошибку - в логах Php не смог найти папку tmp в контейнере 
вылечилось прямыми командами

docker exec -it orbita-php-fpm-1 mkdir -p /vesp/upload
docker exec -it orbita-php-fpm-1 chmod -R 777 /vesp/upload

- почему то эмодзи не подключились не дает выбрать элемент 

а если есть видяшка на сервере можно к енкодеру добавить опцию декодировать с использованием GPU ?

**Comment by bezumkin** [comment]
> а если есть видяшка на сервере можно к енкодеру добавить опцию декодировать с использованием GPU ?

Да, можно указать кодирование через Nvidia в `.env`
```
TRANSCODE_ENCODER=h264_nvenc
```

Ну и прокинуть карту в контейнер через `docker-compose.override.yml`:
```yml
services:
  php-fpm:
    devices:
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
                - compute
                - video
```
